import os
import pytest
from src.run_pipeline import PipelineRunner


def test_pipeline_runner_instantiation():
    runner = PipelineRunner()
    assert runner.config_path == "config/company_profile.yaml"
    assert "CRAWLER" in runner.statuses
    assert "CLEANER" in runner.statuses
    assert "RECOMMENDER" in runner.statuses
    assert "BUILD_SITE" in runner.statuses


def test_pipeline_all_artifacts_exist():
    # Verify all artifacts generated by pipeline exist
    assert os.path.exists("data/raw/crawled_market_news.csv"), "Raw CSV missing"
    assert os.path.exists("data/processed/cleaned_market_news.csv"), "Cleaned CSV missing"
    assert os.path.exists("data/processed/recommended_market_news.csv"), "Recommended CSV missing"
    assert os.path.exists("docs/index.html"), "docs/index.html missing"
    assert os.path.exists("docs/report.json"), "docs/report.json missing"
    assert os.path.exists("logs/pipeline.log"), "logs/pipeline.log missing"
